DemoRest/DemoRest/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainPage.urls')),
    path('api/v1/base-auth/', include('rest_framework.urls')),
    path('api/v1/cars/', include('cars.urls')),
    path('api/v1/auth/', include('djoser.urls')),
    path('api/v1/auth_token/', include('djoser.urls.authtoken')),
]

DemoRest/cars/urls.py
from django.urls import path
from . import views

app_name = 'car'
urlpatterns = [
    path('car/create/', views.CarCreateView.as_view()),
    path('all/', views.CarsListView.as_view()),
    path('car/detail/<int:pk>/', views.CarDetailView.as_view()),
]

DemoRest/mainPage/urls.py
from django.urls import path
from . import views

app_name = 'mainPage'
urlpatterns = [
    path('', views.index, name='home'),
]

DemoRest/cars/models.py
from django.db import models
from django.contrib.auth import get_user_model
User = get_user_model()


class Car(models.Model):
    vin = models.CharField(verbose_name='Вин', db_index=True, unique=True, max_length=64)
    color = models.CharField(verbose_name='Цвет', max_length=64)
    brand = models.CharField(verbose_name='Brand', max_length=64)
    CAR_TYPES = (
        (1, 'Седан'),
        (2, 'Хэчбек'),
        (3, 'Универсал'),
        (4, 'Купе'),
    )
    car_type = models.IntegerField(verbose_name='Car_Type', choices=CAR_TYPES)
    user = models.ForeignKey(User, verbose_name='Пользователь', on_delete=models.CASCADE)

DemoRest/mainPage/models.py
from django.db import models

# Create your models here.

DemoRest/cars/views.py
from django.shortcuts import render
from rest_framework import generics
from . import serializers, models, permissions
from rest_framework.permissions import IsAuthenticated, IsAdminUser
from rest_framework.authentication import TokenAuthentication, SessionAuthentication


class CarCreateView(generics.CreateAPIView):
    serializer_class = serializers.CarDetailSerializer


class CarsListView(generics.ListAPIView):
    serializer_class = serializers.CarListSerializer
    queryset = models.Car.objects.all()
    permission_classes = (IsAuthenticated, IsAdminUser)


class CarDetailView(generics.RetrieveUpdateDestroyAPIView):
    serializer_class = serializers.CarDetailSerializer
    queryset = models.Car.objects.all()
    permission_classes = (permissions.IsOwnerOrReadOnly, IsAdminUser)

DemoRest/mainPage/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'mainPage/index.html')

DemoRest/mainPage/templates/mainPage/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css">
</head>
<body>
    <div class="d-flex flex-column flex-md-row align-items-center pb-3 mb-4 border-bottom">
      <a href="/" class="d-flex align-items-center text-dark text-decoration-none">
        <span class="fs-4">CarStore</span>
      </a>
      <nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto">
        <a class="me-3 py-2 text-dark text-decoration-none" href="{% url 'mainPage:home' %}">Главная</a>
        <a class="me-3 py-2 text-dark text-decoration-none" href="/api/v1/cars/all/">Все машины</a>
      </nav>
        <a class="btn btn-outline-primary" href="/api/v1/base-auth/login/?next=/api/v1/cars/all/">Sign up</a>
    </div>
    <div class="container">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

DemoRest/mainPage/templates/mainPage/index.html
{% extends 'mainPage/base.html' %}

{% block title %}
Главная страница
{% endblock %}

{% block content %}
    <h1>Это автомобильный CRUD</h1>
    <p>Все автомобили тут</p>
{% endblock %}